export const MOCK_USER = {
  id: "user-demo-1",
  email: "sarah@example.com",
  fullName: "Sarah Mitchell",
  phone: "+44 7700 900123",
  avatarUrl: "https://i.pravatar.cc/150?img=47",
  role: "customer" as const,
  isVerified: true,
  verificationBadge: "verified" as const,
  trustScore: 87,
  createdAt: "2024-01-15T10:00:00Z",
};

export const MOCK_CLEANER_USER = {
  id: "user-cleaner-1",
  email: "amara@example.com",
  fullName: "Amara Osei",
  phone: "+44 7700 900456",
  avatarUrl: "https://i.pravatar.cc/150?img=32",
  role: "cleaner" as const,
  isVerified: true,
  verificationBadge: "trusted" as const,
  trustScore: 96,
  createdAt: "2023-08-10T10:00:00Z",
};

export const MOCK_CLEANERS = [
  {
    id: "cleaner-1",
    userId: "user-cleaner-1",
    fullName: "Amara Osei",
    avatarUrl: "https://i.pravatar.cc/150?img=32",
    bio: "5 years of professional cleaning experience. Specialising in Airbnb turnovers and deep cleans. Attention to detail is my signature.",
    serviceTypes: ["standard", "deep_clean", "airbnb_turnover"],
    hourlyRate: 22,
    isAvailable: true,
    isVerified: true,
    verificationBadge: "trusted",
    trustScore: 96,
    repeatBookingRate: 84,
    completionRate: 99,
    responseTime: "< 15 min",
    totalBookings: 412,
    averageRating: 4.9,
    reviewCount: 203,
    wouldWorkAgainPct: 97,
    cancellationRate: 1,
    serviceRadius: 8,
    location: { lat: 51.515, lng: -0.09 },
    distanceKm: 1.2,
    eta: "15 min",
  },
  {
    id: "cleaner-2",
    userId: "user-cleaner-2",
    fullName: "James Adeyemi",
    avatarUrl: "https://i.pravatar.cc/150?img=68",
    bio: "Reliable, professional and thorough. End of tenancy specialist with 7 years experience.",
    serviceTypes: ["standard", "end_of_tenancy", "office"],
    hourlyRate: 20,
    isAvailable: true,
    isVerified: true,
    verificationBadge: "verified",
    trustScore: 91,
    repeatBookingRate: 76,
    completionRate: 97,
    responseTime: "< 30 min",
    totalBookings: 287,
    averageRating: 4.8,
    reviewCount: 142,
    wouldWorkAgainPct: 93,
    cancellationRate: 3,
    serviceRadius: 12,
    location: { lat: 51.52, lng: -0.08 },
    distanceKm: 2.1,
    eta: "22 min",
  },
  {
    id: "cleaner-3",
    userId: "user-cleaner-3",
    fullName: "Nadia Kowalski",
    avatarUrl: "https://i.pravatar.cc/150?img=56",
    bio: "Methodical and meticulous. My clients book me for years, not once.",
    serviceTypes: ["standard", "deep_clean", "recurring"],
    hourlyRate: 24,
    isAvailable: false,
    isVerified: true,
    verificationBadge: "trusted",
    trustScore: 98,
    repeatBookingRate: 91,
    completionRate: 100,
    responseTime: "< 1 hr",
    totalBookings: 634,
    averageRating: 5.0,
    reviewCount: 318,
    wouldWorkAgainPct: 99,
    cancellationRate: 0,
    serviceRadius: 6,
    location: { lat: 51.51, lng: -0.12 },
    distanceKm: 3.4,
    eta: "Available tomorrow",
  },
  {
    id: "cleaner-4",
    userId: "user-cleaner-4",
    fullName: "Marcus Thompson",
    avatarUrl: "https://i.pravatar.cc/150?img=12",
    bio: "Focused on property management clients. I handle everything from regular cleans to emergency turnovers.",
    serviceTypes: ["standard", "airbnb_turnover", "office"],
    hourlyRate: 21,
    isAvailable: true,
    isVerified: true,
    verificationBadge: "verified",
    trustScore: 88,
    repeatBookingRate: 68,
    completionRate: 95,
    responseTime: "< 1 hr",
    totalBookings: 198,
    averageRating: 4.7,
    reviewCount: 89,
    wouldWorkAgainPct: 88,
    cancellationRate: 5,
    serviceRadius: 15,
    location: { lat: 51.505, lng: -0.07 },
    distanceKm: 0.8,
    eta: "8 min",
  },
];

export const MOCK_PROPERTIES = [
  {
    id: "prop-1",
    ownerId: "user-demo-1",
    name: "Shoreditch Studio",
    propertyType: "airbnb",
    addressLine1: "14 Curtain Road",
    city: "London",
    postcode: "EC2A 3NZ",
    photoUrl: "https://images.unsplash.com/photo-1554995207-c18c203602cb?w=400&q=80",
    accessNotes: "Key in lockbox code 4521. Lift to 3rd floor.",
    parkingInfo: "No parking. Nearest paid parking on Old Street.",
    hasLift: true,
    petsInfo: "No pets",
    cleaningFrequency: "weekly",
    bedroomCount: 1,
    bathroomCount: 1,
    sqft: 420,
    qrCodeUrl: `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent("https://ocha.app/book?propertyId=prop-1")}`,
    createdAt: "2024-01-20T10:00:00Z",
  },
  {
    id: "prop-2",
    ownerId: "user-demo-1",
    name: "Canary Wharf Apartment",
    propertyType: "apartment",
    addressLine1: "8 South Quay",
    city: "London",
    postcode: "E14 9RH",
    photoUrl: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=400&q=80",
    accessNotes: "Concierge will let you in. Show ID.",
    parkingInfo: "Visitor parking available in basement, ask concierge.",
    hasLift: true,
    petsInfo: "1 cat (friendly)",
    cleaningFrequency: "biweekly",
    bedroomCount: 2,
    bathroomCount: 2,
    sqft: 780,
    qrCodeUrl: `https://api.qrserver.com/v1/create-qr-code/?size=300x300&data=${encodeURIComponent("https://ocha.app/book?propertyId=prop-2")}`,
    createdAt: "2024-02-01T10:00:00Z",
  },
];

export const MOCK_BOOKINGS = [
  {
    id: "booking-1",
    customerId: "user-demo-1",
    cleanerId: "cleaner-1",
    propertyId: "prop-1",
    serviceType: "airbnb_turnover",
    status: "accepted",
    scheduledAt: new Date(Date.now() + 2 * 86400000).toISOString(),
    estimatedDurationHours: 3,
    totalPrice: 66,
    urgency: "standard",
    notes: "Guests check in at 3pm. Please ensure fresh towels.",
    reviewStatus: "pending",
    customer: MOCK_USER,
    cleaner: MOCK_CLEANERS[0],
    property: MOCK_PROPERTIES[0],
    createdAt: new Date(Date.now() - 86400000).toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: "booking-2",
    customerId: "user-demo-1",
    cleanerId: "cleaner-2",
    propertyId: "prop-2",
    serviceType: "standard",
    status: "completed",
    scheduledAt: new Date(Date.now() - 7 * 86400000).toISOString(),
    estimatedDurationHours: 4,
    totalPrice: 80,
    urgency: "standard",
    notes: "",
    reviewStatus: "pending",
    customer: MOCK_USER,
    cleaner: MOCK_CLEANERS[1],
    property: MOCK_PROPERTIES[1],
    createdAt: new Date(Date.now() - 8 * 86400000).toISOString(),
    updatedAt: new Date(Date.now() - 7 * 86400000).toISOString(),
  },
];

export const MOCK_TRUST_PROFILE = {
  userId: "user-demo-1",
  overallScore: 87,
  verificationStatus: {
    emailVerified: true,
    phoneVerified: true,
    idVerified: false,
    selfieVerified: false,
    addressVerified: false,
    backgroundCheckDone: false,
    paymentVerified: true,
  },
  behavioralMetrics: {
    cancellationRate: 2,
    repeatBookingRate: 74,
    responseSpeed: "< 30 min",
    latePct: 0,
    disputeFrequency: 0,
    wouldWorkAgainPct: 100,
    completionRate: 98,
  },
  badge: "verified" as const,
};

export const MOCK_NOTIFICATIONS = [
  {
    id: "notif-1",
    userId: "user-demo-1",
    type: "booking_accepted" as const,
    title: "Booking confirmed",
    message: "Amara Osei accepted your booking for Shoreditch Studio on Thursday.",
    isRead: false,
    bookingId: "booking-1",
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: "notif-2",
    userId: "user-demo-1",
    type: "review_request" as const,
    title: "Leave a review",
    message: "How was your cleaning session with James Adeyemi? Share your experience.",
    isRead: false,
    bookingId: "booking-2",
    createdAt: new Date(Date.now() - 2 * 86400000).toISOString(),
  },
  {
    id: "notif-3",
    userId: "user-demo-1",
    type: "trust_update" as const,
    title: "Trust score updated",
    message: "Your trust score increased to 87. Keep booking to build your reputation.",
    isRead: true,
    bookingId: undefined,
    createdAt: new Date(Date.now() - 5 * 86400000).toISOString(),
  },
];
